version: '3'
services:
  watcheye:
    build: 
      context: ./app
    container_name: watcheye_app
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    devices:
      - "/dev/video*:/dev/video*"
    environment:
      - QT_X11_NO_MITSHM=1
    privileged: true  # 웹캠 접근 권한을 위해 필요
  proxy:
    image: nginx:1.18
    container_name: watcheye_proxy
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - watcheye