version: '3.8'

services:
  watcheye:
    build: 
      context: ./app
    container_name: watcheye_app
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app
      # - ./data:/data
      # - /tmp/.X11-unix:/tmp/.X11-unix  # X11 소켓 마운트
    devices:
      - "/dev/video0:/dev/video0"
    environment:
      # - DISPLAY=host.docker.internal:0  # MacOS X11 디스플레이 설정
      - OPENCV_LOG_LEVEL=DEBUG  # OpenCV 디버그 로그 활성화
    privileged: true  # 웹캠 접근 권한을 위해 필요

  proxy:
    image: nginx:1.18
    container_name: watcheye_proxy
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - watcheye