version: '3'
services:
  watcheye:
    build: 
      context: ./app
    container_name: watcheye_app
    ports:
      - "8001:8001"
    privileged: true
    volumes:
      - ./app:/app
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /dev/video0:/dev/video0
    devices:
      - /dev/video0:/dev/video0
    environment:
      - QT_X11_NO_MITSHM=1
      - DISPLAY=${DISPLAY}
      - OPENCV_LOG_LEVEL=DEBUG

  proxy:
    image: nginx:1.18
    container_name: watcheye_proxy
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - watcheye
